shift_mananger/urls.py
from django.urls import path
from . import views

app_name = 'shift'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:person_id>/', views.update_shift, name='update_shift'),
]

shift_mananger/models.py
from django.db import models
from django.utils import timezone
import datetime
# from django.forms import ModelForm
from django import forms

# Create your models here.

WEEK_DAYS = [
    ('Sun', 'Sunday'),
    ('Mon', 'Monday'),
    ('Tue', 'Tuesday'),
    ('Wed', 'Wednesday'),
    ('Thu', 'Thursday'),
    ('Fri', 'Friday'),
    ('Sat', 'Saturday'),
]


class Person(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.first_name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Shift(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    day = models.CharField(max_length=10, choices=WEEK_DAYS)
    counter = models.IntegerField(default=0)

    def __str__(self):
        return self.day

class WeekDays(models.Model):
    day_name = models.CharField(max_length=128)
    


class ShiftForm(forms.Form):
    days = forms.MultipleChoiceField(choices=WEEK_DAYS, widget=forms.CheckboxSelectMultiple)

# ------------------------------------------------------------

class User(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Days(models.Model):
    week_day = models.CharField(max_length=100)
    worker = models.ManyToManyField(User, through='Workers')

    def __str__(self):
        return self.week_day


class Workers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    days = models.ForeignKey(Days, on_delete=models.CASCADE)

shift_mananger/forms.py
from django import forms

WEEK_DAYS = (
    ('Sun', 'Sunday'),
    ('Mon', 'Monday'),
    ('Tue', 'Tuesday'),
    ('Wed', 'Wednesday'),
    ('Thu', 'Thursday'),
    ('Fri', 'Friday'),
    ('Sat', 'Saturday'),
)


class NameForm(forms.Form):
    # your_name = forms.CharField(label='Your name', max_length=100)
    # select = forms.ChoiceField(choices=WEEK_DAYS)
    days = forms.MultipleChoiceField(choices=WEEK_DAYS, widget=forms.CheckboxSelectMultiple)

shift_mananger/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Person, Shift, ShiftForm, User, Days, Workers
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import NameForm
from .functions import return_json


# Create your views here.


# class IndexView(generic.ListView):
#     template_name = 'shift_mananger/index.html'
#     context_object_name = 'latest_people_list'

#     def get_queryset(self):
#         return Person.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')

def index(request):
    workers = [{
        'week_day': "Sunday",
        'counter': 0,
        'workers': []
    }, {
        'week_day': "Monday",
        'counter': 0,
        'workers': []
    }, {
        'week_day': "Tuesday",
        'counter': 0,
        'workers': []
    }, {
        'week_day': "Wednesday",
        'counter': 0,
        'workers': []
    }, {
        'week_day': "Thursday",
        'counter': 0,
        'workers': []
    }, {
        'week_day': "Friday",
        'counter': 0,
        'workers': []
    }, {
        'week_day': "Saturday",
        'counter': 0,
        'workers': []
    }]

    db_data = Person.objects.all()
    for people_data in db_data:
        each_person = Person.objects.get(pk=people_data.id)
        get_selected = each_person.shift_set.all()
        for person_counter in get_selected:
            for days in workers:
                if person_counter.counter == 1:
                    if str(days['week_day']) == str(person_counter.get_day_display()):
                        days['counter'] += 1
                        days['workers'].append(each_person)
    return render(request, 'shift_mananger/index.html', {
        'latest_people_list': workers,
        'counter': db_data,
        'people': db_data,
    })


class DetailView(generic.DetailView):
    model = Person
    template_name = 'shift_mananger/detail.html'


def update_shift(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    selected_shift = person.shift_set.all()
    form = ShiftForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        days_array = data['days']
        for selected_days in selected_shift:
            selected_days.counter = 0
            selected_days.save()
            for days in days_array:
                if str(days) == str(selected_days):
                    shift_instance = person.shift_set.get(pk=selected_days.id)
                    shift_instance.counter = 1
                    shift_instance.save()

    else:
        shift_instance = person.shift_set.all()
        for days in shift_instance:
            reset_counter = person.shift_set.get(pk=days.id)
            reset_counter.counter = 0
            reset_counter.save()
        return render(request, 'shift_mananger/detail.html', {
            'person': person,
            'clear_message': "You cleared shift",
        })

    return render(request, 'shift_mananger/detail.html', {
        'person': person,
        'success_message': "Updated was successfully",
    })

shift_mananger/templates/shift_mananger/account_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Settings</title>
</head>
<body>
    <div class="container">

    </div>
</body>
</html>

shift_mananger/templates/shift_mananger/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shift_mananger/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shift_mananger/css/bootstrap-grid.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shift_mananger/css/bootstrap.min.css' %}">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <a style="font-family: sans-serif;color: #6F42C1;" href="{% url 'shift:index' %}">
                    Home
                </a>
                <!-- <a style="font-family: sans-serif;padding-left: 5%;" href="{% url 'shift:index' %}">
                    Account info
                </a> -->
                <div style="font-family: sans-serif;" class="right menu">
                    <p style="padding-left: 30%;color: #6F42C1;">Welcome {{person.first_name}} {{person.last_name}}
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div  class="col-12">
                {% if success_message %}<p><strong style="padding-left: 23%;font-family: sans-serif;"
                        class="text-center">{{ success_message }}</strong></p>
                {% else%}
                {% if clear_message %}<p><strong style="padding-left: 23%;font-family: sans-serif;"
                        class="text-center">{{ clear_message}}</strong></p>
                {% endif %}
                {% endif %}
            </div>
        </div>
        <hr>
        <form action="{% url 'shift:update_shift' person.id %}" method="POST">
            <div class="row">
                <div class="col-12">
                    <div class="custom-control custom-checkbox custom-contro">
                        {% csrf_token %}
                        {% for days in person.shift_set.all %}
                        {% if days.counter %}
                        <input type="checkbox" class="custom-control-input" name="days" id="id_days" value="{{days}}"
                            checked>
                        {% else %}
                        <input type="checkbox" class="custom-control-input" name="days" id="id_days" value="{{days}}">
                        {% endif %}
                        <label style="font-family: sans-serif;" class="custom-control-label"
                            for="days{{ forloop.counter }}">{{days.get_day_display}}</label><br>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
                <div class="col">
                    <div style="padding-top: 3%;" class="justify-content-center">
                        {% if person.shift_set.all %}
                        <button style="font-family: sans-serif;" type="submit" class="btn btn-success">Update</button>
                        {% else %}
                        <p><strong style="font-family: sans-serif;">You don't have working days.</strong></p>
                        {% endif %}
                    </div>
                </div>
                <div class="col"></div>
                <div class="col"></div>
            </div>
            <hr>
        </form>
    </div>
</body>

</html>

shift_mananger/templates/shift_mananger/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shift_mananger/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'shift_mananger/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href=" {% static 'shift_mananger/css/offcanvas.css' %}">
    <title>Home</title>
</head>
<style>
    html,
    body {
        overflow-x: hidden;
        /* Prevent scroll on narrow devices */
    }

    body {
        padding-top: 56px;
    }

    @media (max-width: 767.98px) {
        .offcanvas-collapse {
            position: fixed;
            top: 56px;
            /* Height of navbar */
            bottom: 0;
            width: 100%;
            padding-right: 1rem;
            padding-left: 1rem;
            overflow-y: auto;
            background-color: #000000;
            transition: -webkit-transform .3s ease-in-out;
            transition: transform .3s ease-in-out;
            transition: transform .3s ease-in-out, -webkit-transform .3s ease-in-out;
            -webkit-transform: translateX(100%);
            transform: translateX(100%);
        }

        .offcanvas-collapse.open {
            -webkit-transform: translateX(-1rem);
            transform: translateX(-1rem);
            /* Account for horizontal padding on navbar */
        }
    }

    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
    }

    .nav-scroller .nav {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: nowrap;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        color: rgba(5, 4, 4, 0.75);
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .nav-underline .nav-link {
        padding-top: .75rem;
        padding-bottom: .75rem;
        font-size: .875rem;
        color: #000000;
    }

    .nav-underline .nav-link:hover {
        color: blue;
    }

    .nav-underline .active {
        font-weight: 500;
        color: #000000;
    }

    .text-white-50 {
        color: rgba(255, 255, 255, .5);
    }

    .bg-purple {
        background-color: var(--purple);
    }

    /* .d-flex.align-items-center.p-3.my-3.text-white-50.bg-purple.rounded.box-shadow {} */

    .border-bottom {
        border-bottom: 1px solid #e5e5e5;
    }

    .box-shadow {
        box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05);
    }

    .lh-100 {
        line-height: 1;
    }

    .lh-125 {
        line-height: 1.25;
    }

    .lh-150 {
        line-height: 1.5;
    }
</style>

<body class="bg-light">

    <nav style="padding: 8px 16px;" class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
        <a style="padding-left: 2%;font-family: sans-serif;" class="navbar-brand" href="#">Home</a>
        <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a style="font-family: sans-serif;" class="nav-link" href="#">Profile</a>
                </li>
        </div>
    </nav>

    <div class="nav-scroller bg-white box-shadow">
        <nav class="nav nav-underline">
            <a style="font-family: sans-serif;" class="nav-link active" href="#">Dashboard</a>
            <a class="nav-link" href="#">
                People
                <span style="color: #6C757D;"
                    class="badge badge-pill bg-light align-text-bottom">{{counter.count}}</span>
            </a>
        </nav>
    </div>

    <main role="main" class="container">
        <div style="background-color: #6F42C1;padding: 16px;margin: 16px 0px;"
            class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
            {% load static %}
            <img class="mr-3" src="{% static 'shift_mananger/js/bootstrap-outline.svg' %}" alt="" width="48"
                height="48">
            <div style="padding-left: 3%;" class="lh-100">
                <h6 style="font-family: sans-serif;" class="mb-0 text-white lh-100">Shift Administration</h6>
                <small style="font-family: sans-serif;">To help you with managing your stuff members.</small>
            </div>
        </div>

        {% for stuff in latest_people_list %}
        <ul>
            <li style="font-family: sans-serif;color: #6F42C1;">{{stuff.week_day}}</li>
            {% if stuff.counter %}
            <small style="font-family: sans-serif;color: rgba(0, 0, 0, 0.795);">Number of workers <span
                    style="color: #6F42C1;font-family: sans-serif;"
                    class="badge badge-pill align-text-bottom">{{stuff.counter}}</span></small>
            {% else %}
            <small style="font-family: sans-serif;color: rgba(0, 0, 0, 0.795);">No shifts available<span
                    style="color: #6F42C1;font-family: sans-serif;"></span></small>
            {% endif %}
            {% for person in stuff.workers %}
            <ul>
                <li><a style="font-family: sans-serif;" href="{% url 'shift:detail' person.id %}">@{{person}}</a></li>
            </ul>
            {% endfor %}
            <hr>
        </ul>
        {% endfor %}
        <div class="my-3 p-3 bg-white rounded box-shadow">
            <h6 style="font-family: sans-serif;" class="border-bottom border-gray pb-2 mb-0">Available workers</h6>
            {% for members in people %}
            {% if members%}
            <div class="media text-muted pt-3">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">{{members.first_name}} {{members.last_name}}</strong>
                        <a href="{% url 'shift:detail' members.id %}">Update</a>
                    </div>
                    <!-- <span class="d-block">@{{members.last_name}}</span> -->
                </div>
            </div>
            {% else %}
            <div class="media text-muted pt-3">
                <p style="font-family: sans-serif;">Sorry there are no workers available</p>
            </div>
            {% endif %}
            {% endfor %}

        </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% load static %}
    <script src="{% static 'shift_mananger/js/jquery.slim.min.js' %} "></script>
    <script src="{% static 'shift_mananger/js/popper.min.js' %} "></script>
    <script src="{% static 'shift_mananger/js/bootstrap.min.js' %} "></script>
    <script src="{% static 'shift_mananger/js/bootstrap.js' %} "></script>
    <script src="{% static 'shift_mananger/js/holder.min.js' %} "></script>
    <script src="{% static 'shift_mananger/js/offcanvas.js' %} "></script>
</body>

</html>